# Generated by Django 5.0.1 on 2026-02-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ausleiher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('notizen', models.TextField(blank=True)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ausleiher',
                'verbose_name_plural': 'Ausleiher',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GespeicherterFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filter_json', models.JSONField(default=dict, help_text='Filter als JSON')),
                ('benutzer_id', models.CharField(help_text='Keycloak User ID', max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gespeicherter Filter',
                'verbose_name_plural': 'Gespeicherte Filter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hersteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('notizen', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hersteller',
                'verbose_name_plural': 'Hersteller',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('farbe', models.CharField(default='#8B5CF6', max_length=7)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('erstellt_von', models.CharField(blank=True, max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item-Set',
                'verbose_name_plural': 'Item-Sets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
                ('adresse', models.TextField(blank=True)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('sortierung', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ausleihliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausleiher_name', models.CharField(help_text='Falls nicht aus Datenbank', max_length=200)),
                ('ausleiher_organisation', models.CharField(blank=True, max_length=200)),
                ('zweck', models.CharField(blank=True, max_length=300)),
                ('frist', models.DateField(blank=True, help_text='Rückgabe-Frist', null=True)),
                ('modus', models.CharField(choices=[('global', 'Global (eine Unterschrift)'), ('individuell', 'Individuell (Unterschrift pro Item)')], default='global', max_length=20)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('aktiv', 'Aktiv'), ('teilrueckgabe', 'Teilrückgabe'), ('abgeschlossen', 'Abgeschlossen'), ('abgebrochen', 'Abgebrochen')], default='offen', max_length=20)),
                ('unterschrift_ausleihe', models.TextField(blank=True, help_text='Base64 Signatur')),
                ('unterschrift_rueckgabe', models.TextField(blank=True)),
                ('notizen', models.TextField(blank=True)),
                ('notizen_rueckgabe', models.TextField(blank=True)),
                ('rueckgabe_am', models.DateTimeField(blank=True, null=True)),
                ('rueckgabe_zustand', models.CharField(blank=True, help_text='OK, Beschädigt, etc.', max_length=50)),
                ('erstellt_von', models.CharField(blank=True, max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('ausleiher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausleihen', to='inventar.ausleiher')),
            ],
            options={
                'verbose_name': 'Ausleihliste',
                'verbose_name_plural': 'Ausleihlisten',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='InventarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('seriennummer', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('verfuegbar', 'Verfügbar'), ('ausgeliehen', 'Ausgeliehen'), ('reserviert', 'Reserviert'), ('defekt', 'Defekt')], default='verfuegbar', max_length=20)),
                ('bilder', models.JSONField(blank=True, default=list)),
                ('notizen', models.TextField(blank=True)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('erstellt_von', models.CharField(blank=True, max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('hersteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventar.hersteller')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AusleihePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unterschrift', models.TextField(blank=True)),
                ('zustand_ausleihe', models.CharField(choices=[('ok', 'OK'), ('verschleiss', 'Verschleiß'), ('beschaedigt', 'Beschädigt'), ('defekt', 'Defekt')], default='ok', max_length=20)),
                ('zustand_rueckgabe', models.CharField(blank=True, choices=[('ok', 'OK'), ('verschleiss', 'Verschleiß'), ('beschaedigt', 'Beschädigt'), ('defekt', 'Defekt')], max_length=20)),
                ('foto_ausleihe', models.TextField(blank=True)),
                ('foto_rueckgabe', models.TextField(blank=True)),
                ('ist_zurueckgegeben', models.BooleanField(default=False)),
                ('rueckgabe_am', models.DateTimeField(blank=True, null=True)),
                ('rueckgabe_notizen', models.TextField(blank=True)),
                ('ausleihliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='inventar.ausleihliste')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausleihe_positionen', to='inventar.inventaritem')),
            ],
            options={
                'verbose_name': 'Ausleihe-Position',
                'verbose_name_plural': 'Ausleihe-Positionen',
            },
        ),
        migrations.CreateModel(
            name='InventarKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farbe', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='package', max_length=50)),
                ('beschreibung', models.TextField(blank=True)),
                ('sortierung', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unterkategorien', to='inventar.inventarkategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.AddField(
            model_name='inventaritem',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventar.inventarkategorie'),
        ),
        migrations.CreateModel(
            name='ItemQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('bezeichnung', models.CharField(blank=True, help_text="z.B. 'Hauptaufkleber', 'Ersatz'", max_length=100)),
                ('ist_primaer', models.BooleanField(default=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='inventar.inventaritem')),
            ],
            options={
                'verbose_name': 'QR-Code',
                'verbose_name_plural': 'QR-Codes',
            },
        ),
        migrations.CreateModel(
            name='Reservierung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausleiher_name', models.CharField(max_length=200)),
                ('datum_von', models.DateField()),
                ('datum_bis', models.DateField()),
                ('zweck', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('bestaetigt', 'Bestätigt'), ('storniert', 'Storniert'), ('ausgeliehen', 'In Ausleihe umgewandelt')], default='aktiv', max_length=20)),
                ('notizen', models.TextField(blank=True)),
                ('erstellt_von', models.CharField(blank=True, max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('ausleiher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventar.ausleiher')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservierungen', to='inventar.inventaritem')),
            ],
            options={
                'verbose_name': 'Reservierung',
                'verbose_name_plural': 'Reservierungen',
                'ordering': ['datum_von'],
            },
        ),
        migrations.AddField(
            model_name='inventaritem',
            name='standort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventar.standort'),
        ),
        migrations.CreateModel(
            name='ItemSetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.IntegerField(default=1)),
                ('notizen', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_positionen', to='inventar.inventaritem')),
                ('item_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='inventar.itemset')),
            ],
            options={
                'verbose_name': 'Set-Position',
                'verbose_name_plural': 'Set-Positionen',
                'unique_together': {('item_set', 'item')},
            },
        ),
    ]
