# Generated by Django 5.0.1 on 2026-02-01 18:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kalender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('inventar_nr', models.CharField(blank=True, help_text='Interne Inventarnummer', max_length=50, unique=True)),
                ('seriennummer', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.CharField(blank=True, help_text='Eindeutiger QR-Code', max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('verfuegbar', 'Verfügbar'), ('ausgeliehen', 'Ausgeliehen'), ('reserviert', 'Reserviert'), ('wartung', 'In Wartung'), ('defekt', 'Defekt')], default='verfuegbar', max_length=20)),
                ('zustand', models.CharField(choices=[('neu', 'Neu'), ('sehr_gut', 'Sehr gut'), ('gut', 'Gut'), ('verschleiss', 'Verschleiß'), ('beschaedigt', 'Beschädigt'), ('defekt', 'Defekt'), ('ausgemustert', 'Ausgemustert')], default='gut', max_length=20)),
                ('zustand_notizen', models.TextField(blank=True, help_text='Notizen zum Zustand')),
                ('lagerplatz', models.CharField(blank=True, help_text='z.B. Regal A3, Case 5', max_length=100)),
                ('menge', models.IntegerField(default=1)),
                ('einheit', models.CharField(default='Stück', max_length=20)),
                ('mindestbestand', models.IntegerField(default=0, help_text='Warnung wenn Bestand unterschritten')),
                ('kaufdatum', models.DateField(blank=True, null=True)),
                ('kaufpreis', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lieferant', models.CharField(blank=True, max_length=200)),
                ('garantie_bis', models.DateField(blank=True, null=True)),
                ('aktueller_wert', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('abschreibung_jahre', models.IntegerField(default=5)),
                ('bilder', models.JSONField(blank=True, default=list)),
                ('technische_daten', models.JSONField(blank=True, default=dict, help_text='z.B. Gewicht, Leistung, Anschlüsse')),
                ('letzte_wartung', models.DateField(blank=True, null=True)),
                ('naechste_wartung', models.DateField(blank=True, null=True)),
                ('wartungsintervall_tage', models.IntegerField(default=365)),
                ('notizen', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('erstellt_von', models.CharField(blank=True, max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventar-Item',
                'verbose_name_plural': 'Inventar-Items',
                'ordering': ['kategorie', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lagerort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
                ('adresse', models.TextField(blank=True)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('sortierung', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lagerort',
                'verbose_name_plural': 'Lagerorte',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ausleihe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausleiher_name', models.CharField(max_length=200)),
                ('ausleiher_email', models.EmailField(blank=True, max_length=254)),
                ('ausleiher_telefon', models.CharField(blank=True, max_length=50)),
                ('ausleiher_organisation', models.CharField(blank=True, max_length=200)),
                ('zweck', models.CharField(blank=True, max_length=300)),
                ('ausleihe_von', models.DateTimeField()),
                ('ausleihe_bis', models.DateTimeField()),
                ('tatsaechliche_rueckgabe', models.DateTimeField(blank=True, null=True)),
                ('unterschrift_modus', models.CharField(choices=[('keine', 'Keine Unterschrift'), ('global', 'Eine Unterschrift für alle'), ('individuell', 'Unterschrift pro Item')], default='global', max_length=20)),
                ('unterschrift_ausleihe', models.TextField(blank=True, help_text='Base64-encoded Signatur bei Ausleihe')),
                ('unterschrift_rueckgabe', models.TextField(blank=True, help_text='Base64-encoded Signatur bei Rückgabe')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('aktiv', 'Aktiv/Ausgeliehen'), ('teilrueckgabe', 'Teilrückgabe'), ('zurueckgegeben', 'Zurückgegeben'), ('abgebrochen', 'Abgebrochen')], default='offen', max_length=20)),
                ('notizen_ausleihe', models.TextField(blank=True)),
                ('notizen_rueckgabe', models.TextField(blank=True)),
                ('erstellt_von', models.CharField(blank=True, max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausleihen', to='kalender.event')),
            ],
            options={
                'verbose_name': 'Ausleihe',
                'verbose_name_plural': 'Ausleihen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='AusleihePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.IntegerField(default=1)),
                ('zustand_ausleihe', models.CharField(blank=True, choices=[('neu', 'Neu'), ('sehr_gut', 'Sehr gut'), ('gut', 'Gut'), ('verschleiss', 'Verschleiß'), ('beschaedigt', 'Beschädigt'), ('defekt', 'Defekt'), ('ausgemustert', 'Ausgemustert')], max_length=20)),
                ('zustand_rueckgabe', models.CharField(blank=True, choices=[('neu', 'Neu'), ('sehr_gut', 'Sehr gut'), ('gut', 'Gut'), ('verschleiss', 'Verschleiß'), ('beschaedigt', 'Beschädigt'), ('defekt', 'Defekt'), ('ausgemustert', 'Ausgemustert')], max_length=20)),
                ('unterschrift', models.TextField(blank=True)),
                ('notizen', models.TextField(blank=True)),
                ('ist_zurueckgegeben', models.BooleanField(default=False)),
                ('rueckgabe_am', models.DateTimeField(blank=True, null=True)),
                ('ausleihe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='inventar.ausleihe')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausleihe_positionen', to='inventar.inventaritem')),
            ],
            options={
                'verbose_name': 'Ausleihe-Position',
                'verbose_name_plural': 'Ausleihe-Positionen',
            },
        ),
        migrations.CreateModel(
            name='InventarKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farbe', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='package', max_length=50)),
                ('beschreibung', models.TextField(blank=True)),
                ('sortierung', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unterkategorien', to='inventar.inventarkategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.AddField(
            model_name='inventaritem',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventar.inventarkategorie'),
        ),
        migrations.AddField(
            model_name='inventaritem',
            name='lagerort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventar.lagerort'),
        ),
        migrations.CreateModel(
            name='Wartung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('inspektion', 'Inspektion'), ('reinigung', 'Reinigung'), ('reparatur', 'Reparatur'), ('pruefung', 'Prüfung (z.B. BGV)'), ('update', 'Software/Firmware Update'), ('sonstiges', 'Sonstiges')], default='inspektion', max_length=20)),
                ('datum', models.DateField()),
                ('beschreibung', models.TextField()),
                ('kosten', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dienstleister', models.CharField(blank=True, max_length=200)),
                ('zustand_vorher', models.CharField(blank=True, choices=[('neu', 'Neu'), ('sehr_gut', 'Sehr gut'), ('gut', 'Gut'), ('verschleiss', 'Verschleiß'), ('beschaedigt', 'Beschädigt'), ('defekt', 'Defekt'), ('ausgemustert', 'Ausgemustert')], max_length=20)),
                ('zustand_nachher', models.CharField(blank=True, choices=[('neu', 'Neu'), ('sehr_gut', 'Sehr gut'), ('gut', 'Gut'), ('verschleiss', 'Verschleiß'), ('beschaedigt', 'Beschädigt'), ('defekt', 'Defekt'), ('ausgemustert', 'Ausgemustert')], max_length=20)),
                ('erstellt_von', models.CharField(blank=True, max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wartungen', to='inventar.inventaritem')),
            ],
            options={
                'verbose_name': 'Wartung',
                'verbose_name_plural': 'Wartungen',
                'ordering': ['-datum'],
            },
        ),
    ]
