# Generated by Django 5.0.1 on 2026-02-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahnungsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('betreff', models.CharField(default='Mahnung: Rückgabe überfällig - Ausleihe #{ausleihe_id}', max_length=300)),
                ('text', models.TextField(default='Hallo {ausleiher_name},\n\ndie folgende Ausleihe ist überfällig:\n\nAusleihe #{ausleihe_id}\nFrist: {frist}\nTage überfällig: {tage_ueberfaellig}\n\nAusgeliehene Items:\n{items}\n\nBitte geben Sie die Items schnellstmöglich zurück.\n\nMit freundlichen Grüßen,\nStagedesk')),
                ('ist_standard', models.BooleanField(default=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahnungs-Template',
                'verbose_name_plural': 'Mahnungs-Templates',
            },
        ),
        migrations.AddField(
            model_name='ausleiheposition',
            name='anzahl',
            field=models.IntegerField(default=1, help_text='Ausgeliehene Menge (für mengenbasierte Items)'),
        ),
        migrations.AddField(
            model_name='ausleihliste',
            name='letzte_mahnung_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventaritem',
            name='menge_gesamt',
            field=models.IntegerField(default=1, help_text='Gesamtmenge (1 = Einzelstück)'),
        ),
        migrations.AddField(
            model_name='inventaritem',
            name='menge_verfuegbar',
            field=models.IntegerField(default=1, help_text='Aktuell verfügbare Menge'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktion', models.CharField(choices=[('erstellt', 'Erstellt'), ('aktualisiert', 'Aktualisiert'), ('geloescht', 'Gelöscht'), ('ausgeliehen', 'Ausgeliehen'), ('zurueckgegeben', 'Zurückgegeben'), ('aktiviert', 'Aktiviert'), ('mahnung', 'Mahnung gesendet'), ('importiert', 'Importiert'), ('dupliziert', 'Dupliziert'), ('status_geaendert', 'Status geändert')], max_length=30)),
                ('entity_type', models.CharField(help_text='z.B. item, ausleihliste, reservierung', max_length=50)),
                ('entity_id', models.IntegerField()),
                ('entity_name', models.CharField(blank=True, max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user_keycloak_id', models.CharField(blank=True, max_length=100)),
                ('user_username', models.CharField(blank=True, max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit-Log',
                'verbose_name_plural': 'Audit-Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='inventar_au_entity__3860d9_idx'), models.Index(fields=['-timestamp'], name='inventar_au_timesta_e4aea5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemBild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='inventar_bilder/%Y/%m/')),
                ('ist_haupt', models.BooleanField(default=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_bilder', to='inventar.inventaritem')),
            ],
            options={
                'verbose_name': 'Item-Bild',
                'verbose_name_plural': 'Item-Bilder',
                'ordering': ['-ist_haupt', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='ItemZustandsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zustand_vorher', models.CharField(blank=True, max_length=20)),
                ('zustand_nachher', models.CharField(blank=True, max_length=20)),
                ('typ', models.CharField(choices=[('ausleihe', 'Ausleihe'), ('rueckgabe', 'Rückgabe'), ('manuell', 'Manuell')], max_length=20)),
                ('notizen', models.TextField(blank=True)),
                ('user_keycloak_id', models.CharField(blank=True, max_length=100)),
                ('user_username', models.CharField(blank=True, max_length=150)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('ausleihliste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventar.ausleihliste')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zustandslog', to='inventar.inventaritem')),
            ],
            options={
                'verbose_name': 'Zustandslog',
                'verbose_name_plural': 'Zustandslogs',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
