# Generated by Django 5.0.1 on 2026-02-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventar', '0002_mahnungstemplate_ausleiheposition_anzahl_and_more'),
        ('veranstaltung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausleihliste',
            name='veranstaltung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausleihlisten', to='veranstaltung.veranstaltung'),
        ),
    ]
