# Generated by Django 5.0.1 on 2026-02-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventar', '0003_ausleihliste_veranstaltung'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausleiheposition',
            name='ausleiher_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ausleiheposition',
            name='ausleiher_ort',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ausleihliste',
            name='ausleiher_ort',
            field=models.CharField(blank=True, help_text='Ausleiher Ort (bei Global)', max_length=200),
        ),
        migrations.AddField(
            model_name='ausleihliste',
            name='titel',
            field=models.CharField(blank=True, help_text='Titel der Ausleihliste', max_length=200),
        ),
        migrations.AlterField(
            model_name='ausleihliste',
            name='ausleiher_name',
            field=models.CharField(blank=True, help_text='Ausleiher Name (bei Global)', max_length=200),
        ),
    ]
