# Generated by Django 5.0.1 on 2026-05-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_add_push_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgAufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('laeuft', 'Läuft'), ('fertig', 'Fertig')], default='offen', max_length=20)),
                ('sortierung', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('zugewiesene', models.ManyToManyField(blank=True, related_name='ag_aufgaben', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'AG-Aufgabe',
                'verbose_name_plural': 'AG-Aufgaben',
                'ordering': ['status', 'sortierung', 'id'],
            },
        ),
    ]
