# Generated by Django 5.0.1 on 2026-02-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='discord_channel_id',
            field=models.CharField(blank=True, help_text='Discord Text-Channel ID', max_length=100),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='discord_event_id',
            field=models.CharField(blank=True, help_text='Discord Scheduled Event ID', max_length=100),
        ),
        migrations.AddField(
            model_name='veranstaltunganhang',
            name='unique_key',
            field=models.CharField(blank=True, help_text='Eindeutiger Schlüssel um Duplikate zu verhindern', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='veranstaltungzuweisung',
            name='technik_rolle',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('lichtmeister', 'Lichtmeister'), ('lichtassistent', 'Lichtassistent'), ('tonmeister', 'Tonmeister'), ('tonassistenz', 'Tonassistenz'), ('video', 'Video'), ('kamera', 'Kamera'), ('verfolger', 'Verfolger')], default='', help_text='Optionale Technik-Rolle bei Veranstaltung', max_length=30),
        ),
    ]
