# Generated by Django 5.0.1 on 2026-02-10 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltung', '0002_veranstaltung_discord_channel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaetigkeitsRolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sortierung', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tätigkeitsrolle',
                'verbose_name_plural': 'Tätigkeitsrollen',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='veranstaltungzuweisung',
            name='rolle',
        ),
        migrations.RemoveField(
            model_name='veranstaltungzuweisung',
            name='technik_rolle',
        ),
        migrations.AddField(
            model_name='veranstaltungzuweisung',
            name='taetigkeit',
            field=models.ForeignKey(blank=True, help_text='Tätigkeitszuweisung bei Veranstaltung', null=True, on_delete=django.db.models.deletion.SET_NULL, to='veranstaltung.taetigkeitsrolle'),
        ),
    ]
