# Generated by Django 5.0.1 on 2026-02-10 20:06

from django.db import migrations


def seed_taetigkeitsrollen(apps, schema_editor):
    TaetigkeitsRolle = apps.get_model('veranstaltung', 'TaetigkeitsRolle')
    defaults = [
        ('Lichtmeister', 1),
        ('Lichtassistenz', 2),
        ('Tonmeister', 3),
        ('Tonassistenz', 4),
        ('Video', 5),
        ('Kamera', 6),
        ('Verfolger', 7),
        ('Licht', 8),
        ('Ton', 9),
    ]
    for name, sort in defaults:
        TaetigkeitsRolle.objects.get_or_create(name=name, defaults={'sortierung': sort})


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltung', '0003_taetigkeitsrolle_remove_veranstaltungzuweisung_rolle_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_taetigkeitsrollen, migrations.RunPython.noop),
    ]
