# Generated by Django 5.0.1 on 2026-02-15 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anwesenheit', '0001_initial'),
        ('veranstaltung', '0004_seed_taetigkeitsrollen'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='anwesenheitsliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veranstaltungen', to='anwesenheit.anwesenheitsliste'),
        ),
    ]
