# Generated by Django 5.0.1 on 2026-02-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltung', '0005_veranstaltung_anwesenheitsliste'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeranstaltungTermin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=255)),
                ('datum', models.DateField()),
                ('beginn', models.TimeField(blank=True, null=True)),
                ('ende', models.TimeField(blank=True, null=True)),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termine', to='veranstaltung.veranstaltung')),
            ],
            options={
                'verbose_name': 'Veranstaltungstermin',
                'verbose_name_plural': 'Veranstaltungstermine',
                'ordering': ['datum', 'beginn'],
            },
        ),
    ]
