# Generated by Django 5.0.1 on 2026-03-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltung', '0006_veranstaltungtermin'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeranstaltungVerfuegbarkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_keycloak_id', models.CharField(max_length=100)),
                ('user_username', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('verfuegbar', 'Verfügbar'), ('nicht_verfuegbar', 'Nicht verfügbar'), ('vielleicht', 'Vielleicht')], max_length=20)),
                ('kommentar', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('termin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verfuegbarkeiten', to='veranstaltung.veranstaltungtermin')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verfuegbarkeiten', to='veranstaltung.veranstaltung')),
            ],
            options={
                'verbose_name': 'Verfügbarkeit',
                'verbose_name_plural': 'Verfügbarkeiten',
                'ordering': ['user_username', 'termin'],
                'unique_together': {('veranstaltung', 'user_keycloak_id', 'termin')},
            },
        ),
    ]
