# Generated by Django 5.0.1 on 2026-04-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0001_initial'),
        ('veranstaltung', '0009_meldung_aktiv_abmeldung'),
    ]

    operations = [
        migrations.AddField(
            model_name='taetigkeitsrolle',
            name='erforderliche_kompetenzen',
            field=models.ManyToManyField(blank=True, help_text='Kompetenzen, die User für diese Tätigkeit haben müssen', related_name='erforderlich_fuer_taetigkeiten', to='kompetenzen.kompetenz'),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='empfohlene_kompetenzen',
            field=models.ManyToManyField(blank=True, help_text='Diese Kompetenzen sind hilfreich, aber nicht zwingend', related_name='empfohlen_fuer_veranstaltungen', to='kompetenzen.kompetenz'),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='erforderliche_kompetenzen',
            field=models.ManyToManyField(blank=True, help_text='User brauchen diese Kompetenzen, um sich zu melden', related_name='erforderlich_fuer_veranstaltungen', to='kompetenzen.kompetenz'),
        ),
    ]
