# Generated by Django 5.0.1 on 2026-04-25 14:44

from django.db import migrations, models


def map_old_statuses(apps, schema_editor):
    Veranstaltung = apps.get_model('veranstaltung', 'Veranstaltung')
    # Alle alten Stati außer 'abgesagt' werden zu 'geplant'.
    # laufend/abgeschlossen werden ab jetzt aus datum_von/datum_bis abgeleitet.
    Veranstaltung.objects.exclude(status='abgesagt').update(status='geplant')


def noop_reverse(apps, schema_editor):
    # Reverse: einfach 'geplant' → 'planung' zurückmappen, damit es zum alten Schema passt.
    Veranstaltung = apps.get_model('veranstaltung', 'Veranstaltung')
    Veranstaltung.objects.filter(status='geplant').update(status='planung')


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltung', '0010_taetigkeitsrolle_erforderliche_kompetenzen_and_more'),
    ]

    operations = [
        # Erst Daten migrieren (Choices noch alt), dann das Feld umstellen.
        migrations.RunPython(map_old_statuses, noop_reverse),
        migrations.AlterField(
            model_name='veranstaltung',
            name='status',
            field=models.CharField(choices=[('geplant', 'Geplant'), ('abgesagt', 'Abgesagt')], default='geplant', max_length=20),
        ),
    ]
