# Generated by Django 5.0.1 on 2026-04-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0003_userkompetenz_custom_ablauf_stufen'),
        ('veranstaltung', '0011_simplify_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeranstaltungTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('titel_vorlage', models.CharField(blank=True, help_text='Titel-Vorschlag (wird beim Anlegen vorausgefüllt)', max_length=300)),
                ('beschreibung_vorlage', models.TextField(blank=True)),
                ('ort_vorlage', models.CharField(blank=True, max_length=300)),
                ('dauer_minuten', models.IntegerField(default=120, help_text='Default-Dauer in Minuten (Start = jetzt, Ende = jetzt + dauer)')),
                ('erinnerungen', models.JSONField(blank=True, default=list, help_text='Liste von {zeit_vorher, einheit}')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('erforderliche_kompetenzen', models.ManyToManyField(blank=True, related_name='templates_erforderlich', to='kompetenzen.kompetenz')),
                ('taetigkeiten', models.ManyToManyField(blank=True, related_name='templates', to='veranstaltung.taetigkeitsrolle')),
            ],
            options={
                'verbose_name': 'Veranstaltungs-Template',
                'verbose_name_plural': 'Veranstaltungs-Templates',
                'ordering': ['name'],
            },
        ),
    ]
