# Generated by Django 5.0.1 on 2026-04-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltung', '0012_add_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltungchecklisteitem',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Optionale Frist; rote Markierung wenn überfällig', null=True),
        ),
        migrations.AddField(
            model_name='veranstaltungchecklisteitem',
            name='erinnerung_gesendet',
            field=models.BooleanField(default=False),
        ),
    ]
