# Generated by Django 5.0.1 on 2026-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltung', '0013_add_checkliste_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='discord_channel_aktiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='discord_event_aktiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='discord_info_nachricht_id',
            field=models.CharField(blank=True, help_text='ID der Info-Nachricht im Discord-Info-Channel (für Edit/Delete)', max_length=100),
        ),
    ]
