# Generated by Django 5.0.1 on 2026-05-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_add_push_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('abgeschlossen', 'Abgeschlossen')], default='offen', max_length=20)),
                ('sortierung', models.IntegerField(default=0, help_text='Frei wählbare Reihenfolge — kleiner Wert zuerst')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('zugewiesene', models.ManyToManyField(blank=True, related_name='aufgaben', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['sortierung', 'id'],
            },
        ),
    ]
