# Generated by Django 5.0.1 on 2026-05-17 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aufgaben', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('erledigt', models.BooleanField(default=False)),
                ('sortierung', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='aufgaben.aufgabe')),
            ],
            options={
                'verbose_name': 'Unteraufgabe',
                'verbose_name_plural': 'Unteraufgaben',
                'ordering': ['sortierung', 'id'],
            },
        ),
    ]
