# Generated by Django 5.0.1 on 2026-04-17 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KompetenzKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide-Icon Name', max_length=50)),
                ('farbe', models.CharField(blank=True, help_text='z.B. blue, yellow, red', max_length=20)),
                ('sortierung', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kompetenz-Kategorie',
                'verbose_name_plural': 'Kompetenz-Kategorien',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KompetenzGruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sortierung', models.IntegerField(default=0)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppen', to='kompetenzen.kompetenzkategorie')),
            ],
            options={
                'verbose_name': 'Kompetenz-Gruppe',
                'verbose_name_plural': 'Kompetenz-Gruppen',
                'ordering': ['kategorie__sortierung', 'sortierung', 'name'],
                'unique_together': {('kategorie', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KompetenzBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('typ', models.CharField(choices=[('kategorie_komplett', 'Kategorie komplett'), ('gruppe_komplett', 'Gruppe komplett'), ('anzahl', 'Anzahl Kompetenzen'), ('punkte', 'Punkte-Schwelle')], max_length=30)),
                ('schwelle', models.IntegerField(default=0, help_text='Für Typ anzahl/punkte')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('farbe', models.CharField(blank=True, max_length=20)),
                ('gruppe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kompetenzen.kompetenzgruppe')),
                ('kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kompetenzen.kompetenzkategorie')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Kompetenz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('punkte', models.IntegerField(default=1, help_text='Gewichtung fürs Scoreboard')),
                ('ablauf_stufen', models.JSONField(blank=True, default=list, help_text='Liste von Tagen bis zur nächsten Bestätigung. Leer = Standard.')),
                ('aktiv', models.BooleanField(default=True)),
                ('sortierung', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('gruppe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kompetenzen', to='kompetenzen.kompetenzgruppe')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kompetenzen', to='kompetenzen.kompetenzkategorie')),
            ],
            options={
                'verbose_name': 'Kompetenz',
                'verbose_name_plural': 'Kompetenzen',
                'ordering': ['kategorie__sortierung', 'gruppe__sortierung', 'sortierung', 'name'],
                'unique_together': {('kategorie', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserKompetenz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_keycloak_id', models.CharField(db_index=True, max_length=100)),
                ('user_username', models.CharField(blank=True, max_length=150)),
                ('hat_kompetenz', models.BooleanField(default=False)),
                ('stufe', models.IntegerField(default=0, help_text='Index in ablauf_stufen, steigt bei jeder Bestätigung')),
                ('erworben_am', models.DateTimeField(blank=True, null=True)),
                ('letzte_bestaetigung_am', models.DateTimeField(blank=True, null=True)),
                ('ablauf_am', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bestaetigt_von_username', models.CharField(blank=True, max_length=150)),
                ('notiz', models.TextField(blank=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('kompetenz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_eintraege', to='kompetenzen.kompetenz')),
            ],
            options={
                'verbose_name': 'User-Kompetenz',
                'verbose_name_plural': 'User-Kompetenzen',
                'ordering': ['kompetenz__kategorie__sortierung', 'kompetenz__sortierung'],
                'unique_together': {('user_keycloak_id', 'kompetenz')},
            },
        ),
        migrations.CreateModel(
            name='UserKompetenzHistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_keycloak_id', models.CharField(db_index=True, max_length=100)),
                ('aktion', models.CharField(choices=[('erworben', 'Erworben'), ('bestaetigt', 'Bestätigt'), ('entzogen', 'Entzogen'), ('abgelaufen', 'Abgelaufen')], max_length=20)),
                ('stufe_vorher', models.IntegerField(default=0)),
                ('stufe_nachher', models.IntegerField(default=0)),
                ('notiz', models.TextField(blank=True)),
                ('geaendert_von_username', models.CharField(blank=True, max_length=150)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_kompetenz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie', to='kompetenzen.userkompetenz')),
            ],
            options={
                'verbose_name': 'Kompetenz-Historie',
                'verbose_name_plural': 'Kompetenz-Historien',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
