# Generated by Django 5.0.1 on 2026-04-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KompetenzSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_ablauf_stufen', models.JSONField(blank=True, default=list, help_text='Globaler Default für Ablauf-Stufen. Leer = System-Default.')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kompetenz-Einstellungen',
                'verbose_name_plural': 'Kompetenz-Einstellungen',
            },
        ),
    ]
