# Generated by Django 5.0.1 on 2026-04-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0002_kompetenzsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkompetenz',
            name='custom_ablauf_stufen',
            field=models.JSONField(blank=True, default=list, help_text='User-spezifische Ablauf-Stufen. Leer = nimm Kompetenz- bzw. Global-Default.'),
        ),
    ]
