# Generated by Django 5.0.1 on 2026-04-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompetenzen', '0003_userkompetenz_custom_ablauf_stufen'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompetenz',
            name='voraussetzungen',
            field=models.ManyToManyField(blank=True, help_text='Kompetenzen die der User vorher haben muss', related_name='ermoeglicht', to='kompetenzen.kompetenz'),
        ),
    ]
