# Generated by Django 5.0.1 on 2026-02-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnwesenheitsListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('ort', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('abgeschlossen', 'Abgeschlossen')], default='aktiv', max_length=20)),
                ('erstellt_von_keycloak_id', models.CharField(max_length=100)),
                ('erstellt_von_username', models.CharField(max_length=150)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anwesenheitsliste',
                'verbose_name_plural': 'Anwesenheitslisten',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('anwesend', 'Anwesend'), ('abwesend', 'Abwesend'), ('krank', 'Krank'), ('ausstehend', 'Ausstehend')], default='ausstehend', max_length=20)),
                ('markiert_am', models.DateTimeField(blank=True, null=True)),
                ('markiert_von', models.CharField(blank=True, max_length=150)),
                ('notizen', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnehmer', to='anwesenheit.anwesenheitsliste')),
            ],
            options={
                'verbose_name': 'Teilnehmer',
                'verbose_name_plural': 'Teilnehmer',
                'ordering': ['name'],
                'unique_together': {('liste', 'keycloak_id')},
            },
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=255)),
                ('datum', models.DateField()),
                ('beginn', models.TimeField(blank=True, null=True)),
                ('ende', models.TimeField(blank=True, null=True)),
                ('notizen', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termine', to='anwesenheit.anwesenheitsliste')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['datum', 'beginn'],
                'unique_together': {('liste', 'datum', 'beginn')},
            },
        ),
        migrations.CreateModel(
            name='TerminAnwesenheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('anwesend', 'Anwesend'), ('abwesend', 'Abwesend'), ('krank', 'Krank'), ('ausstehend', 'Ausstehend')], default='ausstehend', max_length=20)),
                ('markiert_am', models.DateTimeField(blank=True, null=True)),
                ('markiert_von', models.CharField(blank=True, max_length=150)),
                ('notizen', models.TextField(blank=True)),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termin_anwesenheiten', to='anwesenheit.teilnehmer')),
                ('termin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anwesenheiten', to='anwesenheit.termin')),
            ],
            options={
                'verbose_name': 'Termin-Anwesenheit',
                'verbose_name_plural': 'Termin-Anwesenheiten',
                'unique_together': {('teilnehmer', 'termin')},
            },
        ),
    ]
