# Generated by Django 5.0.1 on 2026-02-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anwesenheit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='aufgabe',
            field=models.CharField(blank=True, help_text='Zugewiesene Aufgabe/Rolle', max_length=200),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='status',
            field=models.CharField(choices=[('anwesend', 'Anwesend'), ('teilweise', 'Teilweise'), ('abwesend', 'Abwesend'), ('krank', 'Krank'), ('ausstehend', 'Ausstehend')], default='ausstehend', max_length=20),
        ),
        migrations.AlterField(
            model_name='terminanwesenheit',
            name='status',
            field=models.CharField(choices=[('anwesend', 'Anwesend'), ('teilweise', 'Teilweise'), ('abwesend', 'Abwesend'), ('krank', 'Krank'), ('ausstehend', 'Ausstehend')], default='ausstehend', max_length=20),
        ),
    ]
