# Generated by Django 5.0.1 on 2026-02-01 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haushalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monatliches Budget (€)')),
                ('benutzer_id', models.CharField(db_index=True, max_length=255, verbose_name='Keycloak Benutzer-ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Haushalt',
                'verbose_name_plural': 'Haushalte',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon (Emoji)')),
                ('farbe', models.CharField(default='#3B82F6', max_length=7, verbose_name='Farbe (Hex)')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Produktname')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preis (€)')),
                ('anzahl', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Anzahl')),
                ('kategorie', models.CharField(choices=[('konsumitiv', 'Konsumitiv'), ('investiv', 'Investitiv')], default='konsumitiv', max_length=20, verbose_name='Konsumitiv/Investitiv')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Produkt-Link')),
                ('bild_url', models.URLField(blank=True, max_length=500, verbose_name='Bild-URL')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('gekauft_am', models.DateField(blank=True, null=True, verbose_name='Gekauft am')),
                ('haushalt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikel', to='haushalte.haushalt', verbose_name='Haushalt')),
                ('tag_kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haushalte.kategorie', verbose_name='Tag-Kategorie')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
