# Generated by Django 5.0.1 on 2026-02-01 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haushalte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haushalt',
            name='budget',
        ),
        migrations.AddField(
            model_name='haushalt',
            name='budget_investiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget Investitiv (€)'),
        ),
        migrations.AddField(
            model_name='haushalt',
            name='budget_konsumitiv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget Konsumitiv (€)'),
        ),
    ]
