# Generated by Django 5.0.1 on 2026-05-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haushalte', '0002_remove_haushalt_budget_haushalt_budget_investiv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['sortierung', '-erstellt_am'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AddField(
            model_name='artikel',
            name='sortierung',
            field=models.IntegerField(default=0, help_text='Frei wählbare Reihenfolge — kleiner Wert zuerst'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='status',
            field=models.CharField(choices=[('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('bestellt', 'Bestellt'), ('geliefert', 'Geliefert'), ('abgelehnt', 'Abgelehnt')], default='beantragt', max_length=20, verbose_name='Status'),
        ),
    ]
