# Generated by Django 5.0.1 on 2026-05-17 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haushalte', '0003_add_status_sortierung'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='quittung',
            field=models.FileField(blank=True, null=True, upload_to='haushalt/quittungen/%Y/%m/', verbose_name='Quittung/Beleg'),
        ),
        migrations.CreateModel(
            name='ArtikelKommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_keycloak_id', models.CharField(blank=True, max_length=100)),
                ('user_username', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to='haushalte.artikel')),
            ],
            options={
                'verbose_name': 'Artikel-Kommentar',
                'verbose_name_plural': 'Artikel-Kommentare',
                'ordering': ['erstellt_am'],
            },
        ),
    ]
