# Generated by Django 5.0.1 on 2026-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haushalte', '0004_kommentar_quittung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='status',
            field=models.CharField(choices=[('geplant', 'Geplant'), ('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('bestellt', 'Bestellt'), ('geliefert', 'Geliefert'), ('abgelehnt', 'Abgelehnt')], default='geplant', max_length=20, verbose_name='Status'),
        ),
    ]
