# Generated by Django 5.0.1 on 2026-05-18 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haushalte', '0005_status_geplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='quittung',
            field=models.FileField(blank=True, help_text='Einzelne Quittung — für geteilte Quittungen siehe SammelQuittung', null=True, upload_to='haushalt/quittungen/%Y/%m/', verbose_name='Quittung/Beleg'),
        ),
        migrations.CreateModel(
            name='SammelQuittung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('datei', models.FileField(upload_to='haushalt/sammelquittungen/%Y/%m/')),
                ('hochgeladen_von', models.CharField(blank=True, max_length=100)),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('haushalt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sammelquittungen', to='haushalte.haushalt')),
            ],
            options={
                'verbose_name': 'Sammel-Quittung',
                'verbose_name_plural': 'Sammel-Quittungen',
                'ordering': ['-hochgeladen_am'],
            },
        ),
        migrations.AddField(
            model_name='artikel',
            name='sammelquittungen',
            field=models.ManyToManyField(blank=True, related_name='artikel', to='haushalte.sammelquittung', verbose_name='Geteilte Quittungen'),
        ),
    ]
