# Generated by Django 5.0.1 on 2026-02-01 17:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haushalte', '0002_remove_haushalt_budget_haushalt_budget_investiv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farbe', models.CharField(default='#3B82F6', help_text='Hex-Farbcode', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Lucide Icon Name', max_length=50)),
                ('beschreibung', models.TextField(blank=True)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('sortierung', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event-Kategorie',
                'verbose_name_plural': 'Event-Kategorien',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('equipment', 'Equipment'), ('raum', 'Raum/Location'), ('personal', 'Personal/Crew'), ('fahrzeug', 'Fahrzeug'), ('sonstiges', 'Sonstiges')], default='equipment', max_length=20)),
                ('beschreibung', models.TextField(blank=True)),
                ('farbe', models.CharField(default='#6B7280', help_text='Hex-Farbcode', max_length=7)),
                ('ist_verfuegbar', models.BooleanField(default=True)),
                ('max_gleichzeitig', models.IntegerField(default=1, help_text='Wie oft kann diese Ressource gleichzeitig gebucht werden')),
                ('kosten_pro_tag', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('kosten_pro_stunde', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notizen', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressourcen',
                'ordering': ['typ', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('ende', models.DateTimeField()),
                ('ganztaegig', models.BooleanField(default=False)),
                ('ort', models.CharField(blank=True, max_length=300)),
                ('adresse', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('geplant', 'Geplant'), ('bestaetigt', 'Bestätigt'), ('laufend', 'Laufend'), ('abgeschlossen', 'Abgeschlossen'), ('abgesagt', 'Abgesagt')], default='geplant', max_length=20)),
                ('wiederholung', models.CharField(choices=[('keine', 'Keine'), ('taeglich', 'Täglich'), ('woechentlich', 'Wöchentlich'), ('monatlich', 'Monatlich'), ('jaehrlich', 'Jährlich')], default='keine', max_length=20)),
                ('wiederholung_ende', models.DateField(blank=True, help_text='Ende der Wiederholung', null=True)),
                ('geschaetztes_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('verantwortlicher', models.CharField(blank=True, max_length=200)),
                ('teilnehmer_anzahl', models.IntegerField(default=0)),
                ('notizen', models.TextField(blank=True)),
                ('erstellt_von', models.CharField(blank=True, help_text='Keycloak User ID', max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('haushalt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='haushalte.haushalt')),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiederholungen', to='kalender.event')),
                ('kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='kalender.eventkategorie')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='EventErinnerung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit_vorher', models.IntegerField(default=30)),
                ('einheit', models.CharField(choices=[('minuten', 'Minuten'), ('stunden', 'Stunden'), ('tage', 'Tage'), ('wochen', 'Wochen')], default='minuten', max_length=10)),
                ('gesendet', models.BooleanField(default=False)),
                ('gesendet_am', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erinnerungen', to='kalender.event')),
            ],
            options={
                'verbose_name': 'Erinnerung',
                'verbose_name_plural': 'Erinnerungen',
            },
        ),
        migrations.CreateModel(
            name='EventRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.IntegerField(default=1)),
                ('von', models.DateTimeField(help_text='Buchung von (kann vom Event-Zeitraum abweichen)')),
                ('bis', models.DateTimeField(help_text='Buchung bis')),
                ('kosten', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kosten_berechnet', models.BooleanField(default=True, help_text='Kosten automatisch berechnen')),
                ('notizen', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ressourcen', to='kalender.event')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='kalender.ressource')),
            ],
            options={
                'verbose_name': 'Event-Ressource',
                'verbose_name_plural': 'Event-Ressourcen',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='ressourcen',
            field=models.ManyToManyField(blank=True, related_name='events', through='kalender.EventRessource', to='kalender.ressource'),
        ),
    ]
