# Generated by Django 5.0.1 on 2026-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='veranstaltung_id',
            field=models.IntegerField(blank=True, help_text='Veranstaltungs-ID (auto-erstellt)', null=True),
        ),
    ]
