# Generated by Django 5.0.1 on 2026-04-25 20:37

from django.db import migrations, models


def map_old_statuses(apps, schema_editor):
    Event = apps.get_model('kalender', 'Event')
    Event.objects.exclude(status='abgesagt').update(status='geplant')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0002_add_veranstaltung_id_to_event'),
    ]

    operations = [
        migrations.RunPython(map_old_statuses, noop_reverse),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('geplant', 'Geplant'), ('abgesagt', 'Abgesagt')], default='geplant', max_length=20),
        ),
    ]
