# Generated by Django 5.0.1 on 2026-02-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ankuendigung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('prioritaet', models.CharField(choices=[('normal', 'Normal'), ('wichtig', 'Wichtig'), ('dringend', 'Dringend')], default='normal', max_length=20)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('aktiv_von', models.DateTimeField(blank=True, help_text='Ab wann anzeigen (leer = sofort)', null=True)),
                ('aktiv_bis', models.DateTimeField(blank=True, help_text='Bis wann anzeigen (leer = unbegrenzt)', null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ankündigung',
                'verbose_name_plural': 'Ankündigungen',
                'ordering': ['-prioritaet', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='MonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='Stagedesk Monitor', max_length=200)),
                ('untertitel', models.CharField(blank=True, max_length=300)),
                ('logo_url', models.URLField(blank=True, help_text='URL zu einem Logo-Bild')),
                ('hintergrund_farbe', models.CharField(default='#0f172a', help_text='Hex-Farbe', max_length=7)),
                ('zeige_uhr', models.BooleanField(default=True)),
                ('zeige_veranstaltungen', models.BooleanField(default=True, help_text='Nächste und laufende Veranstaltungen')),
                ('zeige_ankuendigungen', models.BooleanField(default=True)),
                ('zeige_onair', models.BooleanField(default=True, help_text='ON AIR Indikator')),
                ('zeige_webuntis', models.BooleanField(default=False)),
                ('zeige_logo', models.BooleanField(default=True)),
                ('webuntis_url', models.URLField(blank=True, help_text='URL zum WebUntis Stundenplan (iFrame)')),
                ('ist_on_air', models.BooleanField(default=False)),
                ('on_air_text', models.CharField(default='ON AIR', max_length=100)),
                ('on_air_seit', models.DateTimeField(blank=True, null=True)),
                ('api_token', models.CharField(blank=True, help_text='Token für externe ON AIR Steuerung', max_length=64, unique=True)),
                ('refresh_intervall', models.IntegerField(default=30, help_text='Sekunden zwischen Auto-Refresh')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitor-Konfiguration',
                'verbose_name_plural': 'Monitor-Konfiguration',
            },
        ),
    ]
