# Generated by Django 5.0.1 on 2026-02-11 17:37

import django.db.models.deletion
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorDatei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('datei', models.FileField(upload_to=monitor.models.monitor_upload_path)),
                ('typ', models.CharField(choices=[('logo', 'Logo'), ('bild', 'Slideshow-Bild'), ('pdf', 'PDF-Datei')], max_length=20)),
                ('reihenfolge', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monitor-Datei',
                'verbose_name_plural': 'Monitor-Dateien',
                'ordering': ['typ', 'reihenfolge', '-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='akzent_farbe',
            field=models.CharField(default='#da1f3d', max_length=7),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='notfall_aktiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='notfall_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='slideshow_intervall',
            field=models.IntegerField(default=10, help_text='Sekunden pro Bild'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='theme_preset',
            field=models.CharField(choices=[('custom', 'Benutzerdefiniert'), ('veranstaltung', 'Veranstaltung'), ('schulbetrieb', 'Schulbetrieb'), ('nacht', 'Nacht')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='ticker_geschwindigkeit',
            field=models.IntegerField(default=50, help_text='Pixel pro Sekunde'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='ticker_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='webuntis_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='webuntis_zoom',
            field=models.IntegerField(default=100, help_text='Zoom in Prozent'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='wetter_api_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='wetter_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='wetter_cache_zeit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='wetter_stadt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_countdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_slideshow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_ticker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_wetter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='hintergrund_farbe',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Fallback-URL wenn kein Upload'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='refresh_intervall',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='webuntis_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='zeige_onair',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='zeige_veranstaltungen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='aktive_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_aktive_pdf', to='monitor.monitordatei'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='aktives_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_aktives_logo', to='monitor.monitordatei'),
        ),
    ]
