# Generated by Django 5.0.1 on 2026-02-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitordatei_monitorconfig_akzent_farbe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='aktives_hintergrundbild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_hintergrundbild', to='monitor.monitordatei'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='freitext_inhalt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='freitext_titel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='qr_code_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='URL für den QR-Code'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_freitext',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_hintergrundbild',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_qr_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitordatei',
            name='typ',
            field=models.CharField(choices=[('logo', 'Logo'), ('bild', 'Slideshow-Bild'), ('pdf', 'PDF-Datei'), ('hintergrund', 'Hintergrundbild')], max_length=20),
        ),
    ]
