# Generated by Django 5.0.1 on 2026-02-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_monitorconfig_aktives_hintergrundbild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='bildschirmschoner_timeout',
            field=models.IntegerField(default=5, help_text='Minuten bis Bildschirmschoner'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='eigener_countdown_datum',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='eigener_countdown_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='raumplan_benutzername',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='raumplan_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='raumplan_cache_zeit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='raumplan_passwort',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='raumplan_raum',
            field=models.CharField(blank=True, help_text='Raum-Kürzel z.B. Aul', max_length=50),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='raumplan_schule',
            field=models.CharField(blank=True, help_text='Schulname in WebUntis', max_length=100),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='raumplan_server',
            field=models.CharField(blank=True, help_text='z.B. katharineum.webuntis.com', max_length=200),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='seitenrotation_intervall',
            field=models.IntegerField(default=30, help_text='Sekunden pro Seite'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='seitenrotation_seiten',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_bildschirmschoner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_eigener_countdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_raumplan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_seitenrotation',
            field=models.BooleanField(default=False),
        ),
    ]
