# Generated by Django 5.0.1 on 2026-02-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_oepnv_api_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='on_air_vollbild',
            field=models.BooleanField(default=False, help_text='Bei ON AIR automatisch Vollbild-Anzeige'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='oepnv_dauer',
            field=models.IntegerField(default=60, help_text='Minuten vorausschauen'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='oepnv_max_abfahrten',
            field=models.IntegerField(default=20, help_text='Max Abfahrten pro Station'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='oepnv_stationen',
            field=models.JSONField(blank=True, default=list, help_text='[{"id": "...", "name": "...", "filter_linien": [], "filter_richtung": "", "zeige_bus": true, "zeige_bahn": true, "zeige_fernverkehr": true}]'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='on_air_farbe',
            field=models.CharField(blank=True, help_text='Leer = Akzentfarbe', max_length=7),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='zeitplan',
            field=models.JSONField(blank=True, default=list, help_text='[{"tage": [0-6], "von": "HH:MM", "bis": "HH:MM"}]'),
        ),
    ]
