# Generated by Django 5.0.1 on 2026-02-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_monitorconfig_on_air_vollbild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_auto_scroll',
            field=models.BooleanField(default=False, help_text='Auto-Scroll bei vielen Abfahrten'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_farbcodierung',
            field=models.BooleanField(default=True, help_text='Farbcodierte Zeitanzeige'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_highlight_naechste',
            field=models.BooleanField(default=True, help_text='Nächste Abfahrt hervorheben'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_schriftgroesse',
            field=models.CharField(choices=[('normal', 'Normal'), ('gross', 'Groß (HD)'), ('4k', 'Sehr groß (4K)')], default='gross', help_text='Schriftgröße für Abfahrtsanzeige', max_length=10),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerungsbanner',
            field=models.BooleanField(default=True, help_text='Störungsbanner anzeigen'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_zeige_relativ',
            field=models.BooleanField(default=True, help_text='Relative Zeit (in X min) anzeigen'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_zeige_via',
            field=models.BooleanField(default=False, help_text='Zwischenhalte anzeigen'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='oepnv_stationen',
            field=models.JSONField(blank=True, default=list, help_text='[{"id": "...", "name": "...", "filter_linien": [], "filter_richtung": "", "zeige_bus": true, "zeige_bahn": true, "zeige_fernverkehr": true, "wegzeit_minuten": 0}]'),
        ),
    ]
