# Generated by Django 5.0.1 on 2026-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_oepnv_display_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_layout_spalten',
            field=models.IntegerField(default=3, help_text='Anzahl Spalten im Layout (1-4)'),
        ),
    ]
