# Generated by Django 5.0.1 on 2026-02-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_oepnv_layout_spalten'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_streik_aktiv',
            field=models.BooleanField(default=False, help_text='Streik-Modus aktivieren'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_streik_linien',
            field=models.JSONField(blank=True, default=list, help_text="Ausgeblendete Linien (z.B. ['Bus 1', 'RE80'])"),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_streik_text',
            field=models.CharField(blank=True, default='', help_text='Streik-Banner Text', max_length=300),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_streik_typen',
            field=models.JSONField(blank=True, default=list, help_text="Ausgeblendete Typen (z.B. ['bus', 're'])"),
        ),
    ]
