# Generated by Django 5.0.1 on 2026-03-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_oepnv_streik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildschirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Eingang, Lehrerzimmer', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('zeitplan', models.JSONField(blank=True, default=list, help_text='[{"profil_id": 3, "tage": [0-6], "von": "HH:MM", "bis": "HH:MM"}]')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('default_profil', models.ForeignKey(blank=True, help_text='Fallback-Profil wenn kein Zeitplan greift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_default_bildschirm', to='monitor.monitorconfig')),
            ],
            options={
                'verbose_name': 'Bildschirm',
                'verbose_name_plural': 'Bildschirme',
                'ordering': ['name'],
            },
        ),
    ]
