# Generated by Django 5.0.1 on 2026-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_bildschirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildschirm',
            name='power_off',
            field=models.CharField(blank=True, default='', help_text='Ausschaltzeit HH:MM (HDMI-CEC)', max_length=5),
        ),
        migrations.AddField(
            model_name='bildschirm',
            name='power_on',
            field=models.CharField(blank=True, default='', help_text='Einschaltzeit HH:MM (HDMI-CEC)', max_length=5),
        ),
    ]
