# Generated by Django 5.0.1 on 2026-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_bildschirm_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildschirm',
            name='cec_status',
            field=models.CharField(blank=True, default='', help_text='Letzter CEC-Status vom Pi (on/standby/unknown)', max_length=20),
        ),
        migrations.AddField(
            model_name='bildschirm',
            name='cec_status_zeit',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt der letzten CEC-Status-Meldung', null=True),
        ),
    ]
