# Generated by Django 5.0.1 on 2026-04-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_power_zeitplan_ferien'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='baukasten_spalten',
            field=models.IntegerField(default=24, help_text='Grid-Spalten (12-48)'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='baukasten_zeilenhoehe',
            field=models.IntegerField(default=40, help_text='Pixel pro Grid-Einheit'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='kamera_titel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='kamera_typ',
            field=models.CharField(choices=[('img', 'MJPEG / Bild-Stream'), ('video', 'HLS / MP4'), ('iframe', 'iframe / Embed')], default='img', max_length=10),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='kamera_url',
            field=models.URLField(blank=True, help_text='HLS/MJPEG-Stream oder iframe-URL'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='layout_widgets',
            field=models.JSONField(blank=True, default=list, help_text='[{"i": "uid", "type": "uhr|...", "x": 0, "y": 0, "w": 4, "h": 4, "config": {}}]'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='zeige_kamera',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='layout_modus',
            field=models.CharField(choices=[('standard', 'Standard-Layout'), ('stundenplan', 'Stundenplan-Vollbild'), ('onair', 'ON AIR Display'), ('abfahrten', 'Abfahrtsmonitor (ÖPNV)'), ('baukasten', 'Widget-Baukasten (frei)')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='Klausur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='Klausur', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Optionaler Zusatztext')),
                ('aktiv_von', models.DateTimeField()),
                ('aktiv_bis', models.DateTimeField()),
                ('farbe', models.CharField(default='#1e40af', help_text='Hintergrundfarbe (Hex)', max_length=7)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('bildschirme', models.ManyToManyField(blank=True, help_text='Auf welchen Bildschirmen angezeigt', related_name='klausuren', to='monitor.bildschirm')),
            ],
            options={
                'verbose_name': 'Klausur',
                'verbose_name_plural': 'Klausuren',
                'ordering': ['-aktiv_von'],
            },
        ),
    ]
