# Generated by Django 5.0.1 on 2026-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_klausur_kamera_baukasten'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildschirm',
            name='power_modus',
            field=models.CharField(choices=[('auto', 'Automatisch (Zeitplan)'), ('manuell_an', 'Manuell — Immer An'), ('manuell_aus', 'Manuell — Immer Aus')], default='auto', max_length=20),
        ),
    ]
