# Generated by Django 5.0.1 on 2026-07-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_add_power_modus'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='aktives_bild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_aktives_bild', to='monitor.monitordatei'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='pdf_intervall',
            field=models.IntegerField(default=10, help_text='Sekunden pro Seite (Durchschalten)'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='pdf_modus',
            field=models.CharField(choices=[('durchschalten', 'Seiten automatisch durchschalten'), ('statisch', 'Feste Seite anzeigen'), ('seiten', 'Nur bestimmte Seiten')], default='durchschalten', max_length=20),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='pdf_pro_ansicht',
            field=models.IntegerField(default=1, help_text='Seiten pro Ansicht (1 oder 2)'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='pdf_seiten',
            field=models.CharField(blank=True, default='', help_text="Seiten-Auswahl, z.B. '1,3,5-7'. Leer = alle.", max_length=200),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='pdf_statische_seite',
            field=models.IntegerField(default=1, help_text="Feste Seite (Modus 'statisch')"),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='vollbild_header',
            field=models.BooleanField(default=False, help_text='Vollbild-Layouts: Standard-Header (Titel/Logo) oben einblenden'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='kamera_typ',
            field=models.CharField(choices=[('img', 'MJPEG / Bild-Stream'), ('video', 'MP4 / nativer Video-Stream'), ('hls', 'HLS-Stream (.m3u8, z.B. RTSP via go2rtc-Bridge)'), ('iframe', 'iframe / Embed')], default='img', max_length=10),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='layout_modus',
            field=models.CharField(choices=[('standard', 'Standard-Layout'), ('stundenplan', 'Stundenplan-Vollbild'), ('onair', 'ON AIR Display'), ('abfahrten', 'Abfahrtsmonitor (ÖPNV)'), ('baukasten', 'Widget-Baukasten (frei)'), ('pdf_vollbild', 'PDF-Vollbild'), ('bild_vollbild', 'Bild-Vollbild')], default='standard', max_length=20),
        ),
    ]
