# Generated by Django 5.0.1 on 2026-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_monitorconfig_aktives_bild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='split_links',
            field=models.CharField(choices=[('klausur', 'Klausur'), ('onair', 'On Air'), ('webuntis', 'WebUntis'), ('uhr', 'Uhr'), ('leer', 'Leer')], default='klausur', help_text='Inhalt der linken Split-Seite', max_length=20),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='split_links_prozent',
            field=models.IntegerField(default=50, help_text='Breite der linken Seite in Prozent (20–80)'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='split_rechts',
            field=models.CharField(choices=[('klausur', 'Klausur'), ('onair', 'On Air'), ('webuntis', 'WebUntis'), ('uhr', 'Uhr'), ('leer', 'Leer')], default='webuntis', help_text='Inhalt der rechten Split-Seite', max_length=20),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='webuntis_url_1tag',
            field=models.URLField(blank=True, help_text='Kompakter Link (nur 1 Tag) — wird im Splitscreen genutzt'),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='layout_modus',
            field=models.CharField(choices=[('standard', 'Standard-Layout'), ('stundenplan', 'Stundenplan-Vollbild'), ('onair', 'ON AIR Display'), ('abfahrten', 'Abfahrtsmonitor (ÖPNV)'), ('baukasten', 'Widget-Baukasten (frei)'), ('pdf_vollbild', 'PDF-Vollbild'), ('bild_vollbild', 'Bild-Vollbild'), ('split', 'Splitscreen')], default='standard', max_length=20),
        ),
    ]
