# Generated by Django 5.0.1 on 2026-08-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_monitorconfig_split_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUntisLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=800)),
                ('notiz', models.CharField(blank=True, max_length=300)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WebUntis-Link',
                'verbose_name_plural': 'WebUntis-Links',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='klausur',
            name='anzeige_modus',
            field=models.CharField(choices=[('vollbild', 'Vollbild (Klausur-Hinweis)'), ('split', 'Splitscreen (Klausur + Stundenplan)'), ('standard', 'Kein Zwang (Profil-Layout)')], default='vollbild', help_text='Wie der Bildschirm während der Klausur aussieht', max_length=10),
        ),
        migrations.AddField(
            model_name='klausur',
            name='split_prozent',
            field=models.IntegerField(default=50, help_text='Breite der Klausur-Seite in Prozent'),
        ),
        migrations.AddField(
            model_name='klausur',
            name='split_seite',
            field=models.CharField(choices=[('links', 'Links'), ('rechts', 'Rechts')], default='links', help_text='Auf welcher Seite die Klausur steht (Split)', max_length=6),
        ),
        migrations.AddField(
            model_name='klausur',
            name='webuntis_link',
            field=models.ForeignKey(blank=True, help_text='Stundenplan-Link für den Split während der Klausur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_klausur_link', to='monitor.webuntislink'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='webuntis_link',
            field=models.ForeignKey(blank=True, help_text='Gespeicherter Link (2 Tage) — überschreibt webuntis_url', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_profil_link', to='monitor.webuntislink'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='webuntis_link_1tag',
            field=models.ForeignKey(blank=True, help_text='Gespeicherter Link (1 Tag) — überschreibt webuntis_url_1tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_profil_link_1tag', to='monitor.webuntislink'),
        ),
    ]
