# Generated by Django 5.0.1 on 2026-08-22 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_webuntislink_klausur_anzeige_modus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBildschirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bildschirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_zuweisungen', to='monitor.bildschirm')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_zuweisungen', to='monitor.monitorconfig')),
            ],
            options={
                'verbose_name': 'Event-Bildschirm-Zuweisung',
                'verbose_name_plural': 'Event-Bildschirm-Zuweisungen',
            },
        ),
        migrations.CreateModel(
            name='MonitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('beschreibung', models.CharField(blank=True, max_length=300)),
                ('farbe', models.CharField(default='#7c3aed', help_text='Akzentfarbe (Hex)', max_length=7)),
                ('aktiv', models.BooleanField(default=False, help_text='Manuell aktiviert')),
                ('aktiv_von', models.DateTimeField(blank=True, help_text='Optional: automatisch aktiv ab (leer = nur manuell)', null=True)),
                ('aktiv_bis', models.DateTimeField(blank=True, help_text='Optional: automatisch aktiv bis', null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('bildschirme', models.ManyToManyField(blank=True, related_name='events', through='monitor.EventBildschirm', to='monitor.bildschirm')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-aktiv', 'name'],
            },
        ),
        migrations.AddField(
            model_name='eventbildschirm',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zuweisungen', to='monitor.monitorevent'),
        ),
        migrations.AlterUniqueTogether(
            name='eventbildschirm',
            unique_together={('event', 'bildschirm')},
        ),
    ]
