# Generated by Django 5.0.1 on 2026-08-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_eventbildschirm_monitorevent_eventbildschirm_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='sortierung',
            field=models.IntegerField(default=0, help_text='Reihenfolge in der Profil-Liste'),
        ),
    ]
