# Generated by Django 5.0.1 on 2026-08-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_monitorconfig_sortierung'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wetter_api_key', models.CharField(blank=True, default='', max_length=64)),
                ('raumplan_server', models.CharField(blank=True, default='', max_length=200)),
                ('raumplan_schule', models.CharField(blank=True, default='', max_length=200)),
                ('raumplan_benutzername', models.CharField(blank=True, default='', max_length=200)),
                ('raumplan_passwort', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Globale Monitor-Einstellung',
                'verbose_name_plural': 'Globale Monitor-Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='KlausurVorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dauer_minuten', models.IntegerField(default=90, help_text='Dauer ab jetzt')),
                ('titel', models.CharField(default='Klausur', max_length=200)),
                ('text', models.TextField(blank=True)),
                ('farbe', models.CharField(default='#1e40af', max_length=7)),
                ('anzeige_modus', models.CharField(choices=[('vollbild', 'Vollbild (Klausur-Hinweis)'), ('split', 'Splitscreen (Klausur + Stundenplan)'), ('standard', 'Kein Zwang (Profil-Layout)')], default='vollbild', max_length=10)),
                ('split_seite', models.CharField(default='links', max_length=6)),
                ('split_prozent', models.IntegerField(default=50)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('webuntis_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_vorlage_link', to='monitor.webuntislink')),
            ],
            options={
                'verbose_name': 'Klausur-Vorlage',
                'verbose_name_plural': 'Klausur-Vorlagen',
                'ordering': ['name'],
            },
        ),
    ]
