# Generated by Django 5.0.1 on 2026-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_monitorglobalsettings_klausurvorlage'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='bild_fit',
            field=models.CharField(choices=[('contain', 'Einpassen (ganzes Bild sichtbar)'), ('cover', 'Füllen (Bildschirm ausfüllen, ggf. beschnitten)'), ('fill', 'Strecken (verzerrt auf Bildschirmgröße)')], default='contain', help_text='Wie das Bild auf den Bildschirm skaliert wird', max_length=10),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='on_air_split',
            field=models.BooleanField(default=False, help_text='Bei ON AIR Splitscreen (ON AIR + Stundenplan) statt reinem Vollbild'),
        ),
    ]
