# Generated by Django 5.0.1 on 2026-08-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_monitorconfig_bild_fit_monitorconfig_on_air_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='on_air_split_seite',
            field=models.CharField(choices=[('links', 'Links'), ('rechts', 'Rechts')], default='rechts', help_text='Auf welcher Seite ON AIR im Splitscreen steht', max_length=6),
        ),
        migrations.AlterField(
            model_name='klausur',
            name='split_seite',
            field=models.CharField(choices=[('links', 'Links'), ('rechts', 'Rechts')], default='rechts', help_text='Auf welcher Seite die Klausur steht (Split)', max_length=6),
        ),
        migrations.AlterField(
            model_name='klausurvorlage',
            name='split_seite',
            field=models.CharField(default='rechts', max_length=6),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='split_links',
            field=models.CharField(choices=[('klausur', 'Klausur'), ('onair', 'On Air'), ('webuntis', 'WebUntis'), ('uhr', 'Uhr'), ('leer', 'Leer')], default='webuntis', help_text='Inhalt der linken Split-Seite', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitorconfig',
            name='split_rechts',
            field=models.CharField(choices=[('klausur', 'Klausur'), ('onair', 'On Air'), ('webuntis', 'WebUntis'), ('uhr', 'Uhr'), ('leer', 'Leer')], default='klausur', help_text='Inhalt der rechten Split-Seite', max_length=20),
        ),
    ]
