# Generated by Django 5.0.1 on 2026-08-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0026_monitorconfig_on_air_split_seite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildschirm',
            name='override_bis',
            field=models.DateTimeField(blank=True, help_text='Optionales Ablaufdatum des Overrides; leer = bis manuell zurückgesetzt', null=True),
        ),
        migrations.AddField(
            model_name='bildschirm',
            name='override_profil',
            field=models.ForeignKey(blank=True, help_text='Sofort-Override: erzwingt diese Ansicht (vor Event/Zeitplan)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_override_bildschirm', to='monitor.monitorconfig'),
        ),
    ]
