# Generated by Django 5.0.1 on 2026-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_bildschirm_override_bis_bildschirm_override_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='bild_fokus_x',
            field=models.IntegerField(default=50, help_text='Fokuspunkt X in Prozent (Modus Füllen)'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='bild_fokus_y',
            field=models.IntegerField(default=50, help_text='Fokuspunkt Y in Prozent (Modus Füllen)'),
        ),
    ]
