# Generated by Django 5.0.1 on 2026-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_monitorconfig_bild_fokus_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('benutzer', models.CharField(blank=True, default='', max_length=150)),
                ('aktion', models.CharField(max_length=60)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Monitor-Protokoll',
                'verbose_name_plural': 'Monitor-Protokoll',
                'ordering': ['-zeitpunkt'],
            },
        ),
    ]
