# Generated by Django 5.0.1 on 2026-08-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0029_monitorauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='geloescht_am',
            field=models.DateTimeField(blank=True, help_text='Papierkorb: gesetzt = gelöscht', null=True),
        ),
        migrations.AddField(
            model_name='monitordatei',
            name='geloescht_am',
            field=models.DateTimeField(blank=True, help_text='Papierkorb: gesetzt = gelöscht', null=True),
        ),
        migrations.CreateModel(
            name='MonitorConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.JSONField(default=dict)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versionen', to='monitor.monitorconfig')),
            ],
            options={
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
