# Generated by Django 5.0.1 on 2026-08-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0030_monitorconfig_geloescht_am_monitordatei_geloescht_am_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitorAuditLog',
        ),
    ]
