# Generated by Django 5.0.1 on 2026-08-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0031_delete_monitorauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerung_bahn',
            field=models.BooleanField(default=True, help_text='Zug-Störungen (NAH.SH HAFAS)'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerung_bahn_linien',
            field=models.JSONField(blank=True, default=list, help_text="Zug-Linienfilter, z.B. ['RE8','RB85']. Leer = alle mit erkennbarer Linie."),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerung_bus',
            field=models.BooleanField(default=True, help_text='Bus-Störungen (Stadtverkehr Lübeck)'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerung_bus_linien',
            field=models.JSONField(blank=True, default=list, help_text="Bus-Linienfilter, z.B. ['1','3','16']. Leer = alle."),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerung_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerung_cache_zeit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerung_manuell',
            field=models.JSONField(blank=True, default=list, help_text="Manuelle Meldungen: [{'titel':..., 'text':...}]"),
        ),
    ]
