# Generated by Django 5.0.1 on 2026-08-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0032_monitorconfig_oepnv_stoerung_bahn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerung_ausgeblendet',
            field=models.JSONField(blank=True, default=list, help_text='IDs manuell ausgeblendeter Störungen (auto-bereinigt wenn Meldung verschwindet)'),
        ),
        migrations.AddField(
            model_name='monitorconfig',
            name='oepnv_stoerung_position',
            field=models.CharField(default='unten', help_text="Störungs-Anzeige: 'unten' (Streifen) oder 'spalte' (eigene Spalte)", max_length=10),
        ),
    ]
