# Generated by Django 5.0.1 on 2026-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0033_monitorconfig_oepnv_stoerung_ausgeblendet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildschirm',
            name='neu_laden_zeit',
            field=models.DateTimeField(blank=True, help_text='Wird beim Reload-Knopf gesetzt; das Display lädt sich neu wenn dieser Wert steigt.', null=True),
        ),
    ]
