# Generated by Django 5.0.1 on 2026-02-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Eindeutiger Permission-Code', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Anzeigename', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Permission')),
                ('category', models.CharField(default='general', help_text='Kategorie für Gruppierung', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Berechtigung',
                'verbose_name_plural': 'Berechtigungen',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Hat Admin-Rechte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permission')),
            ],
            options={
                'verbose_name': 'Rolle',
                'verbose_name_plural': 'Rollen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_id', models.CharField(help_text='Keycloak User Sub ID', max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('theme', models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode'), ('system', 'System')], default='dark', max_length=20)),
                ('theme_locked', models.BooleanField(default=False, help_text='Theme vom Admin festgelegt')),
                ('forced_theme', models.CharField(blank=True, choices=[('dark', 'Dark Mode'), ('light', 'Light Mode'), ('system', 'System')], help_text='Vom Admin erzwungenes Theme', max_length=20, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='users.role')),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Globale Einstellung',
                'verbose_name_plural': 'Globale Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_session_id', models.CharField(max_length=200, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Sitzung',
                'verbose_name_plural': 'Sitzungen',
                'ordering': ['-last_activity'],
            },
        ),
    ]
