# Generated by Django 5.0.1 on 2026-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Lokale Permissions zusätzlich zu Keycloak-Rollen', related_name='users', to='users.permission'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
