# Generated by Django 5.0.1 on 2026-02-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_roles_userprofile_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord User-ID für Event-Verknüpfung', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='technik_arten',
            field=models.CharField(blank=True, help_text='Kommagetrennte Technik-Arten: licht,ton,flexibel', max_length=200),
        ),
    ]
