# Generated by Django 5.0.1 on 2026-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_discord_id_userprofile_technik_arten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sortierung', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='technik_arten',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bereiche',
            field=models.ManyToManyField(blank=True, help_text='Bereiche des Technikers', related_name='users', to='users.bereich'),
        ),
    ]
