# Generated by Django 5.0.1 on 2026-02-10 20:06

from django.db import migrations


def seed_bereiche(apps, schema_editor):
    Bereich = apps.get_model('users', 'Bereich')
    defaults = [
        ('Licht', 1),
        ('Ton', 2),
        ('Video', 3),
        ('Kamera', 4),
    ]
    for name, sort in defaults:
        Bereich.objects.get_or_create(name=name, defaults={'sortierung': sort})


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bereich_remove_userprofile_technik_arten_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_bereiche, migrations.RunPython.noop),
    ]
