# Generated by Django 5.0.1 on 2026-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_bereiche'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Neue User bekommen diese Gruppe automatisch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='groups', to='users.permission')),
            ],
            options={
                'verbose_name': 'Berechtigungsgruppe',
                'verbose_name_plural': 'Berechtigungsgruppen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permission_groups',
            field=models.ManyToManyField(blank=True, help_text='Gruppen für gebündelte Berechtigungen', related_name='users', to='users.permissiongroup'),
        ),
    ]
