# Generated by Django 5.0.1 on 2026-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_permissiongroup_userprofile_permission_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin_cached',
            field=models.BooleanField(default=False, help_text='Zuletzt erkannter Admin-Status aus Keycloak'),
        ),
    ]
