# Generated by Django 5.0.1 on 2026-04-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_is_admin_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Vorname aus Keycloak (given_name)', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Nachname aus Keycloak (family_name)', max_length=150),
        ),
    ]
