# Generated by Django 5.0.1 on 2026-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dashboard_widgets',
            field=models.JSONField(blank=True, default=None, help_text='User-gewählte Dashboard-Widgets (Liste von Codes)', null=True),
        ),
    ]
