# Generated by Django 5.0.1 on 2026-04-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_dashboard_widgets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('zuweisung', 'Zuweisung'), ('mahnung', 'Mahnung'), ('erinnerung', 'Erinnerung'), ('kompetenz', 'Kompetenz'), ('deadline', 'Deadline'), ('konflikt', 'Konflikt'), ('info', 'Info'), ('system', 'System')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Frontend-Pfad, z.B. /veranstaltung/42', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['user', 'read_at'], name='users_notif_user_id_02c2a2_idx')],
            },
        ),
    ]
