# Generated by Django 5.0.1 on 2026-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_landing',
            field=models.CharField(blank=True, default='', help_text='Startseite nach Login, z.B. /veranstaltung', max_length=200),
        ),
    ]
