# Generated by Django 5.0.1 on 2026-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_ical_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_disabled',
            field=models.JSONField(blank=True, default=list, help_text='Deaktivierte Benachrichtigungs-Kategorien (kind), z.B. ["kompetenz"]'),
        ),
    ]
